name: mds
description: App for mds

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #UI
  flutter_svg: ^0.23.0+1

  #Navigation
  auto_route: ^4.0.1

  #DI
  provider: ^6.0.1

  #Architecture
  bloc: ^8.0.1
  flutter_bloc: ^8.0.1

  #Audio
  just_audio: ^0.9.21
  audio_service: ^0.18.4
  audio_session: ^0.1.6+1

  #Utils
  intl: ^0.17.0
  freezed: ^2.0.3
  url_launcher: ^6.1.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.3.0
  spider: ^2.0.0
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.14
  dio: ^4.0.6
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^4.0.0
  json_serializable: ^6.0.1
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/images/jpg/
    - assets/catalog.json
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/common/generated
